### ISSUE TITLE
Cooperation proposal: ArchImage + DEB packages

### ISSUE THREAD

**Issue by ivan-hc** [TasMania17/Gimp-Appimages-Made-From-Debs#3]
Hi, we haven't spoken in a long time.

I saw your work, really amazing. It's now almost impossible to recover old plugins and pieces of software like python2 to make them work on new systems, but you did it: congratulations!

I too, in my own way, am working on GIMP AppImage, as you well know, and have switched to Arch Linux as a basis, and to a container, JuNest, which allows the use of these new programs even on more old distributions.

I saw that you published a new version of GIMP with support for Python2 and related plugins just a few hours ago, and I decided to test it and try to take some parts to insert them into my package, and something seems to show signs of life.

I propose you combine efforts, I provide you with an ArchImage base and you join the missing parts to make it work your way.

I have already inserted Python2 inside, all it miss are "pygtk", the "gimp-python" plugins and... something else that only you, the GIMP expert, know. My use of it is very basic, and only a few days ago I did more research to better understand how it works.

I know that your AppImages are very much oriented towards users of more recent GNU/Linux distributions, but my ArchImages can also work on distributions with kernel 2.6 (therefore very old).

I am already distributing the basic "Stable" version from the Arch Linux repositories and the Developer Edition version from "ChaoticAUR", so they have the basic functions and are not oriented towards professional use like yours.

I also saw that yours are particularly large, if we combine your work with mine, the version that I call "FULL" could solve many problems, from size to compatibility with all distributions.

Do you want to try?

This is my new script to build GIMP Stable as a "hybrid" build https://github.com/ivan-hc/GIMP-appimage/blob/main/gimp-hybrid.sh

You can download and test the pre-release from https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-hybrid

You can also build it on your PC using the script I linked above (see the last workflow run [here](https://github.com/ivan-hc/GIMP-appimage/actions/workflows/GIMP-HYBRID.yml)).

Let me know.

**Comment by TasMania17** [comment]
Hi Ivan, good to hear from you again :)  You gave me the idea of uploading the 'python2 tree' which I added on this appimage. Thanks for your offer to collaborate, I'm retired and can't take on more stuff. I'm still a maintainer at MathMap which I update sometimes. It's written in c and I can't write c but I can work out why things don't work. I compile it and make deb packs. That's why MathMap is in some of these appimages.

I use Gimp all the time and Ubuntu now has it as deb packs, snap files (which are really signed appimages), flatpacks and appimages. It's quite crowded :) I feel I'm in a big ecosystem of all the distros built on Debian. The Gimp developers  use flatpacks and everything is in there but it is just a big collection of files.

Your scripting skills are amazing but I can't do appimages like that. Using the Shradiko script I give it a deb file and it wgets all the dependent files and the deps of deps. In theory it's rock-solid because it's part of the distribution. Ubuntu make Snaps which are just signed appimages. That had to happen. (In this world you can't rely on trust :))
I found-out Snaps can be run on Windows and Macs inside a Linux subsystem.
https://snapcraft.io/docs/build-on-windows
Also Ubuntu is releasing an OS in 2024  built from snaps. It's not for desktops but for other devices. (the rockridge filesystem has come a long way) 
The Ubuntu Gimp snap is 1.2Gb in size but is compressed to around 300Mb. A lot of is not necessary but thinning and testing is probably too time consuming. I recon there is a lot of duplicated files in an OS built from snaps. :)

**Comment by ivan-hc** [comment]
Here is not much work to do on my side.

I have tested some files from your build by drag-drom there where they were missing, and when I had an error I had to search the missing files and libraries. Sometime The scripts where looking for an older library libx2.so when on Arch Linux was already the version libx3.so, all I had to do was to symlink that and the things were working better.

In this script I wrote, all I have done to import python2 was to download and merge via `rsync` the precompiled files from a tar archive. If there are Precompiled plugins and libraries somewhere, we can save them and keep them for the newer builds. All the workflow run will do is to merge these files into the AppDir an everything should work quite well.

Are you able to intercept these files? I think it would be easier with something like [pkg2appimage](https://github.com/AppImageCommunity/pkg2appimage), it is not just an appimage builder, but also a dependency downloader and helper in these cases. If you know a source where we can take these .deb packages, we will have the job easier.

**Comment by ivan-hc** [comment]
@TasMania17 I've finally published the Hybrid release with Python2 support.

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-hybrid

This is the script i use to build it https://github.com/ivan-hc/GIMP-appimage/blob/main/gimp-hybrid.sh it is the same of the Stable release, but with a part which includes a patch using binaries, libraries and files from Debian 10 "Buster" (oldstable), you can download the archive from here:

https://github.com/ivan-hc/GIMP-appimage/releases/tag/gimp-plugins-patches-for-the-hybrid-release

if we can include other binaries like this, we can put the same kind of function in the script.

Anyway, thank you for your attention. I can close this issue / request of support. see you next!

**Comment by TasMania17** [comment]
good outcome :)
